// quotes.js
// Mission CA Nov 2026 - Motivation Engine

const MOTIVATION = {

    quotes: [

        "Small progress every day. Big results in November.",
        "Discipline beats motivation.",
        "The future CA in you is counting on today's effort.",
        "One chapter today is one less chapter tomorrow.",
        "Done is better than perfect.",
        "Stay consistent. Results will follow.",
        "Focus on today's work, not tomorrow's worries.",
        "Success is built one study session at a time.",
        "Your competition is your yesterday.",
        "Dreams require discipline.",
        "Keep showing up.",
        "The hard days create strong people.",
        "Don't stop because it's difficult.",
        "The finish line is worth it.",
        "Every page you read matters.",
        "You don't have to be perfect. Just consistent.",
        "The chapter won't finish itself.",
        "Future you will thank present you.",
        "One more lecture. One more step.",
        "You are closer than you think.",
        "Study now. Celebrate later.",
        "Today's effort becomes tomorrow's confidence.",
        "Trust the process.",
        "One hour today saves three tomorrow.",
        "Stay patient.",
        "Tiny improvements create huge results.",
        "Believe in your preparation.",
        "Keep stacking small wins.",
        "Momentum starts with one chapter.",
        "Keep moving forward.",
        "Consistency compounds.",
        "Every tick mark is progress.",
        "You can do difficult things.",
        "Focus. Finish. Repeat.",
        "Action removes anxiety.",
        "Progress over perfection.",
        "Every revision counts.",
        "Keep your promise to yourself.",
        "One more problem solved.",
        "The best investment is in yourself.",
        "Be proud of today's effort.",
        "Great things take time.",
        "You are writing your own success story.",
        "Success loves preparation.",
        "Stay hungry to learn.",
        "The goal is worth every sacrifice.",
        "Keep your eyes on November.",
        "The journey is the reward.",
        "Don't quit halfway.",
        "Show up even when you don't feel like it.",
        "Your consistency is your superpower.",
        "Every chapter completed is a victory.",
        "Don't count the hours. Make the hours count.",
        "Confidence comes from preparation.",
        "Strong habits create strong results.",
        "Today's discipline is tomorrow's freedom.",
        "Every lecture finished is momentum gained.",
        "Keep the promises you make to yourself.",
        "There is no shortcut to mastery.",
        "The pain of studying is temporary.",
        "Regret lasts longer than hard work.",
        "Choose discipline over excuses.",
        "Start before you feel ready.",
        "Progress happens one decision at a time.",
        "You're building something amazing.",
        "Hard work always leaves a mark.",
        "Keep your standards high.",
        "Greatness is ordinary work done consistently.",
        "Stay focused on your mission.",
        "Success begins with today's choices.",
        "Every revision strengthens your memory.",
        "One page at a time.",
        "Every session matters.",
        "Success is earned, not given.",
        "Your future is built today.",
        "Focus creates results.",
        "Don't wait for motivation.",
        "Create momentum.",
        "Study like your future depends on it.",
        "Keep climbing.",
        "Trust yourself.",
        "Good things take repetition.",
        "Stay calm. Stay focused.",
        "Keep learning.",
        "Never underestimate small progress.",
        "The goal remains the same.",
        "You are capable.",
        "Success starts now.",
        "Stay committed.",
        "The next chapter is waiting.",
        "One more step today.",
        "Keep believing.",
        "Progress never lies.",
        "The effort always shows.",
        "Strong minds finish what they start.",
        "November belongs to the prepared.",
        "Every completed chapter is one less thing to fear.",
        "Your books are building your future.",
        "Success is a habit, not an event.",
        "Stay stronger than your excuses.",
        "One lecture today. One step closer.",
        "The clock keeps ticking. Keep studying.",
        "Progress is silent but powerful.",
        "Discipline creates confidence.",
        "Nothing changes until you do.",
        "The best students simply refuse to quit.",
        "You are investing in yourself.",
        "Every revision sharpens your mind.",
        "Make today's effort count.",
        "The next hour matters.",
        "Keep chasing excellence.",
        "Small victories become big achievements.",
        "Don't rush. Stay consistent.",
        "Focus on progress, not pressure.",
        "One more question solved.",
        "Keep your standards higher than your excuses.",
        "Every minute has value.",
        "You have survived harder days.",
        "This chapter is temporary. Your career is forever.",
        "Nothing worth having comes easy.",
        "Every study session adds up.",
        "Success belongs to the persistent.",
        "Stay disciplined even when no one is watching.",
        "The secret is consistency.",
        "Build habits your future self will admire.",
        "One day you'll thank yourself.",
        "Hard work compounds.",
        "Every page matters.",
        "Stay locked in.",
        "You are becoming stronger every day.",
        "Your effort never goes to waste.",
        "Focus is your greatest advantage.",
        "Ignore distractions.",
        "The goal is closer than yesterday.",
        "Believe in the boring days.",
        "Greatness is built quietly.",
        "Show yourself what you're capable of.",
        "Don't fear the syllabus.",
        "Finish what you start.",
        "Every answer you practice builds confidence.",
        "Stay curious.",
        "You don't need perfect days.",
        "Consistency beats talent.",
        "Winning starts with showing up.",
        "Stay patient with yourself.",
        "The next revision is easier than the first.",
        "Momentum loves action.",
        "Your future employer won't see today's struggle, only tomorrow's success.",
        "Push through discomfort.",
        "You only fail when you stop.",
        "Study because your dreams deserve it.",
        "Stay determined.",
        "Nothing can replace preparation.",
        "Choose progress today.",
        "Keep your mission alive.",
        "You are capable of more than you think.",
        "Great careers begin with disciplined mornings.",
        "Today's work becomes tomorrow's confidence.",
        "Every solved problem is a victory.",
        "Don't compare your Chapter 3 to someone else's Chapter 30.",
        "One focused hour beats three distracted ones.",
        "Silence your excuses.",
        "Stay committed to the mission.",
        "Every revision strengthens recall.",
        "Your dream deserves consistency.",
        "Stay hungry for improvement.",
        "Work now. Relax later.",
        "One lecture can change your confidence.",
        "Trust your effort.",
        "Build momentum daily.",
        "Every tick on the checklist is a promise kept.",
        "Keep showing yourself what's possible.",
        "Success starts with starting.",
        "Stay relentless.",
        "Preparation removes fear.",
        "Keep collecting small victories.",
        "Don't underestimate ordinary days.",
        "Your consistency is becoming your identity.",
        "Stay uncomfortable. That's where growth lives.",
        "Every chapter finished is a reason to smile.",
        "You don't need luck when you're prepared.",
        "Study first. Celebrate later.",
        "There is power in routine.",
        "One more page.",
        "One more revision.",
        "One more attempt.",
        "One more win.",
        "Stay disciplined through the ordinary.",
        "The dream is still alive.",
        "You are building a life, not just passing an exam.",
        "Stay focused on the bigger picture.",
        "Every sunrise is another opportunity to improve.",
        "Keep writing your success story.",
        "Discipline is choosing what you want most over what you want now.",
        "You didn't come this far to only come this far.",
        "Every chapter you complete reduces your stress.",
        "Be patient with yourself.",
        "The work you do today becomes tomorrow's confidence.",
        "Don't let comfort steal your dreams.",
        "Every study session is a deposit into your future.",
        "Consistency always wins eventually.",
        "One more page can change everything.",
        "Stay loyal to your goals.",
        "Your discipline is stronger than your mood.",
        "The future belongs to those who prepare.",
        "Study because your future self deserves it.",
        "No one can study for you.",
        "Your biggest competition is procrastination.",
        "The syllabus gets smaller every day you study.",
        "You become what you repeatedly do.",
        "Choose effort over excuses.",
        "Focus on today's mission.",
        "Keep the promises you make to yourself.",
        "One lecture completed is progress.",
        "Stay hungry for success.",
        "Nothing worth having is ever easy.",
        "Every revision makes you sharper.",
        "Great things grow slowly.",
        "The discomfort is temporary.",
        "Confidence grows from preparation.",
        "Every question solved is a lesson learned.",
        "Don't waste today's opportunity.",
        "Future success starts today.",
        "You are capable of extraordinary things.",
        "Keep learning even when it's boring.",
        "Success is earned quietly.",
        "Your future family will thank today's effort.",
        "Become obsessed with improvement.",
        "The chapter won't defeat you.",
        "Every hour matters.",
        "Don't fear difficult subjects.",
        "Mastery comes from repetition.",
        "Stay focused. Stay humble.",
        "Every day is a fresh start.",
        "Your notebook is becoming your success story.",
        "One decision can change your future.",
        "Keep believing in your journey.",
        "Don't let temporary feelings make permanent decisions.",
        "You are stronger than your excuses.",
        "Work in silence.",
        "Results will make the noise.",
        "A little progress every day adds up.",
        "Keep sharpening your mind.",
        "Every minute invested is never wasted.",
        "Discipline creates freedom.",
        "Stay present.",
        "Study with intention.",
        "Stay curious enough to learn.",
        "Every answer teaches something.",
        "Don't rush greatness.",
        "Success is waiting at the finish line.",
        "Keep writing.",
        "Keep solving.",
        "Keep revising.",
        "One chapter closer.",
        "Focus creates confidence.",
        "You're becoming more prepared every day.",
        "Preparation beats panic.",
        "The effort always pays back.",
        "Don't let fear control your future.",
        "Believe the process.",
        "Keep improving 1% every day.",
        "The exam rewards consistency.",
        "Show discipline today.",
        "Success begins before the exam.",
        "Don't stop until you're proud.",
        "Every tick is a victory.",
        "You deserve the success you're working for.",
        "One revision now saves stress later.",
        "Nothing is impossible with consistency.",
        "Keep climbing your mountain.",
        "Focus on solutions.",
        "Build habits that build success.",
        "The finish line is getting closer.",
        "Stay positive.",
        "Stay productive.",
        "Keep your momentum alive.",
        "Progress is addictive.",
        "The best time to study is now.",
        "Don't delay greatness.",
        "You're creating opportunities.",
        "The difficult roads create strong people.",
        "Every page has value.",
        "Stay determined until the end.",
        "One study session at a time.",
        "Small wins create unstoppable momentum.",
        "Your effort inspires your future.",
        "Never stop believing.",
        "Great achievements require ordinary discipline.",
        "Your dreams are worth today's sacrifice.",
        "You are preparing for a lifetime, not just an exam.",
        "Stay disciplined, even when motivation disappears.",
        "The best investment is your education.",
        "Study like someone else's seat depends on it—because yours does."

    ],

    ahead: [

        "🔥 Amazing! You're ahead of schedule.",
        "Excellent work. Keep this momentum alive.",
        "Outstanding consistency!",
        "You're creating breathing room for yourself.",
        "Fantastic! Future you is smiling.",
        "You're proving that discipline works.",
        "Keep pushing while the momentum is high.",
        "You're doing better than expected.",
        "Stay humble. Stay hungry.",
        "This is how toppers are made.",
        "You're making your future easier.",
        "Outstanding discipline!",
        "Keep building this lead.",
        "You're proving consistency wins.",
        "Fantastic pace!",
        "You earned this confidence.",
        "You're setting yourself up for success.",
        "Excellent planning!",
        "Momentum is on your side.",
        "Keep going—you're inspiring yourself.",
        "You're crushing your weekly target!",
        "Outstanding! Keep this pace.",
        "You're creating a safety cushion.",
        "Amazing consistency!",
        "The future CA is showing up already.",
        "You're ahead because you chose discipline.",
        "Keep making your future easier.",
        "Excellent planning is paying off.",
        "Nothing can stop this momentum.",
        "You're on fire today!"


    ],

    onTrack: [

        "✅ Excellent! You're exactly where you should be.",
        "Consistency wins every time.",
        "Keep repeating what works.",
        "One day at a time.",
        "You're building something great.",
        "Stay steady.",
        "Keep the streak alive.",
        "The plan is working.",
        "Keep trusting the process.",
        "You're on the right path.",
        "Exactly where you need to be.",
        "Keep stacking days like this.",
        "The routine is paying off.",
        "You're doing great.",
        "Steady progress wins races.",
        "Another productive day.",
        "Keep trusting yourself.",
        "Stay focused.",
        "Excellent consistency.",
        "Keep moving forward.",
        "Perfect pace. Keep going.",
        "You're exactly where you planned to be.",
        "Steady work creates amazing results.",
        "Keep repeating successful days.",
        "You're building confidence daily.",
        "Stay patient with the process.",
        "Every day like today matters.",
        "Excellent discipline.",
        "You're making solid progress.",
        "Keep stacking wins."

    ],

    behind: [

        "💪 You're only one study session away from momentum.",
        "Don't worry about yesterday. Win today.",
        "One focused hour changes everything.",
        "Start small.",
        "One chapter is enough for today.",
        "Action beats overthinking.",
        "Don't quit because of one bad day.",
        "You still have plenty of time.",
        "Get started. That's the hardest part.",
        "You've come too far to stop now.",
        "A comeback starts with one chapter.",
        "Don't chase perfection. Chase progress.",
        "There's still time.",
        "Take a deep breath and begin.",
        "The hardest chapter is the one you haven't started.",
        "Don't let one bad day become two.",
        "Start now. Momentum will follow.",
        "One completed task changes everything.",
        "You only need today's effort.",
        "Believe in your comeback.",
        "Today's chapter is tomorrow's relief.",
        "The comeback starts now.",
        "Forget yesterday. Focus on today.",
        "Progress doesn't require perfection.",
        "You only need one productive hour.",
        "Every expert was once behind.",
        "You can still finish strong.",
        "Keep moving forward.",
        "The mission isn't over.",
        "Believe in today's effort."

    ],

    completed: [

        "🎉 Week completed! Amazing work.",
        "Mission accomplished!",
        "Another week closer to becoming a CA.",
        "Celebrate today's success.",
        "Outstanding dedication!",
        "You earned this feeling.",
        "The hard work is paying off.",
        "Excellent consistency!",
        "Keep this energy for next week.",
        "You're unstoppable.",
        "Another week conquered!",
        "You showed up all week. Amazing.",
        "Keep collecting victories.",
        "You earned your break.",
        "Celebrate this achievement.",
        "Your discipline is paying dividends.",
        "Success looks good on you.",
        "One week stronger.",
        "Keep becoming unstoppable.",
        "The mission continues next week.",
        "Week complete! Time to recharge.",
        "Another milestone unlocked.",
        "Excellent dedication this week.",
        "The hard work showed.",
        "Keep this streak alive.",
        "Mission accomplished. Onto the next one!",
        "Consistency always wins.",
        "This is what discipline looks like.",
        "You're becoming unstoppable.",
        "Celebrate your progress—you earned it."

    ]

};

// ----------------------------
// Helper Functions
// ----------------------------

function getRandomItem(array) {
    return array[Math.floor(Math.random() * array.length)];
}

function getRandomQuote() {
    return getRandomItem(MOTIVATION.quotes);
}

function getAheadMessage() {
    return getRandomItem(MOTIVATION.ahead);
}

function getOnTrackMessage() {
    return getRandomItem(MOTIVATION.onTrack);
}

function getBehindMessage() {
    return getRandomItem(MOTIVATION.behind);
}

function getCompletedMessage() {
    return getRandomItem(MOTIVATION.completed);
}